//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaJobs
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuncionarioProjeto
    {
        public int IdFuncionarioProjeto { get; set; }
        public int IdFuncionario { get; set; }
        public int IdVagaProjeto { get; set; }
        public int Ativo { get; set; }
    
        public virtual Funcionario Funcionario { get; set; }
        public virtual VagaProjeto VagaProjeto { get; set; }
    }
}
