//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaJobs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portfolio
    {
        [Key]
        public int IdPorfolio { get; set; }
        public string Titulo { get; set; }
        public string Descricao { get; set; }
        public string Imagem { get; set; }
        public Nullable<int> TempoTrabalho { get; set; }
        public Nullable<int> IdFuncionario { get; set; }
    
        public virtual Funcionario Funcionario { get; set; }
    }
}
