//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaJobs
{
    using SistemaJobs.ViewModels;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HiredItEntities : DbContext
    {
        public HiredItEntities()
            : base("name=HiredItEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Funcionario> Funcionario { get; set; }
        public virtual DbSet<Portfolio> Portfolio { get; set; }
        public virtual DbSet<Cargos> Cargos { get; set; }
        public virtual DbSet<VagaProjeto> VagaProjeto { get; set; }
        public virtual DbSet<Competencias> Competencias { get; set; }
        public virtual DbSet<VmFuncionarioEmpresa> VmFuncionarioEmpresa { get; set; }
    }
}
