//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaJobs
{
    using System;
    using System.Collections.Generic;
    
    public partial class VagaProjeto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VagaProjeto()
        {
            this.Cargos1 = new HashSet<Cargos>();
            this.Competencias1 = new HashSet<Competencias>();
            this.FuncionarioProjeto = new HashSet<FuncionarioProjeto>();
        }
    
        public int IdVagaProjeto { get; set; }
        public string Titulo { get; set; }
        public string Descricao { get; set; }
        public decimal SalarioOrcamento { get; set; }
        public int QtdVagas { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
        public string RegimeContratacao { get; set; }
        public System.DateTime DataFinal { get; set; }
        public int IdEmpresa { get; set; }
        public string TipoVaga { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cargos> Cargos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Competencias> Competencias1 { get; set; }
        public virtual Empresa Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FuncionarioProjeto> FuncionarioProjeto { get; set; }
    }
}
