//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaJobs
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class VagaProjeto
    {
        public int IdVagaProjeto { get; set; }
        [Required]
        [MaxLength(100)]
        public string Titulo { get; set; }
        [Required]
        [MaxLength(300)]
        public string Descricao { get; set; }
        [Required(ErrorMessage = "O campo é obrigatório, não digitar centavos")]
        public decimal SalarioOrcamento { get; set; }
        [Required]
        [MaxLength(200)]
        public string Competencias { get; set; }
        [Required]
        public int QtdVagas { get; set; }
        [Required]
        [MaxLength(100)]
        public string Cidade { get; set; }
        [Required]
        [MinLength(2)]
        [MaxLength(2)]
        public string Estado { get; set; }
        [MaxLength(50)]
        public string RegimeContratacao { get; set; }
        [Required]
        public System.DateTime DataFinal { get; set; }
        public int IdCargos { get; set; }
    
        public virtual Cargos Cargos { get; set; }
    }
}
